# W1D3 训练一：BST 查找与新增

CC      = gcc
CFLAGS  = -g -Wall
TARGET  = bst_train1

$(TARGET): main.c
	$(CC) $(CFLAGS) main.c -o $(TARGET)

.PHONY: clean run
run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET)
